### ISSUE TITLE
Using CocoaPod to install, UIView does not have a member named 'makeToast'

### ISSUE THREAD

**Issue by dwalintukan** [Rannie/Toast-Swift#11]
I integrated the Cocoapod and when trying call the makeToast method like so:

`self.view.makeToast(message: "test", duration: GlobalVars.TOAST_DURATION, position: GlobalVars.TOAST_POSITION)`

I receive a warning that says **'UIView' does not have a member named 'makeToast'**. I did the `import ToastSwift` for that class as well.

Also, it does not recognize the constants, HRToastPosition.

How do I fix this?

**Comment by Rannie** [comment]
~> 0.1.3 has resolved some problem.

**Comment by dwalintukan** [comment]
I am still having the same issue, even after the 0.1.3 update.

**Comment by germanger** [comment]
I'm having this issue too.

1. Installed with cocoapod
2. import ToastSwift in one of my view controllers
3. self.view.makeToast("blah") inside viewDidLoad() throws error: "UIView does not have a member named makeToast"

**Comment by logy-bai** [comment]
i also have this issue. how to fix it?

**Comment by spavezv** [comment]
Having the same problem. Did same steps as @germanger

**Comment by Rannie** [comment]
Use pods need new api like Toast.makeToast(xxxView, msg: msg)... so don't use pods now.I will design new api recently.
