### ISSUE TITLE
Question: can I call makeToast from a UITableViewController?

### ISSUE THREAD

**Issue by germanger** [Rannie/Toast-Swift#12]
Can I call `self.view.makeToastActivityWithMessage("Loading")` from a `UITableViewController` ?

Or it must be called from a `ViewController`?
I ask because, as you know, `UITableViewController` only contains 1 view (a `UITableView`)

**Comment by Rannie** [comment]
UITableViewController is a subclass of UIViewController, so u can call "[self.view xxx]".
