### ISSUE TITLE
How to call from Table Cell button action?

### ISSUE THREAD

**Issue by paulcanning** [Rannie/Toast-Swift#13]
I have a UITableViewController and inside each cell is a button.

I am using an addTarget to attach a handler for the buttons, and inside the handler, I am using self.view.makeToast(), but the toast doesn't display.

I assume it is due to using self.view inside the handler.

Any ideas on how to get this to work?

Thanks!

**Comment by Rannie** [comment]
Cell need handle action and pass to controller?
