### ISSUE TITLE
Toast message does not resize based on content

### ISSUE THREAD

**Issue by DrkCloudStrife** [Rannie/Toast-Swift#38]
I updated HRToast + UIView.swift from previous Swift 3 to latest Swift 4 support and I noticed that long toast messages no longer resize the toast message view.

Swift 3:
![image](https://user-images.githubusercontent.com/98049/33631382-02f92e7e-d9d0-11e7-8e6d-d3eebbce7309.png)

Swift 4:
![image](https://user-images.githubusercontent.com/98049/33631557-888de228-d9d0-11e7-9a4c-e928f2e9060b.png)

I'm not too familiar with Swift and I'm still learning but I noticed that the issue comes from `let desiredSize = toast.systemLayoutSizeFitting(UILayoutFittingCompressedSize)`. I tested this on iOS 10.1.

**Comment by gburlet** [comment]
Same issue.

**Comment by oduconge** [comment]
same issue.

**Comment by sapna197** [comment]
Thanks for help this solution worked for me .
